home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

windshild/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
from django_otp.plugins.otp_totp.models import TOTPDevice
from django_otp.admin import OTPAdminSite
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import StaticViewSitemap 

sitemaps = {
    'static': StaticViewSitemap
}

from home import views


class OTPAdmin(OTPAdminSite):
    pass


admin_site = OTPAdmin(name="OTPAdmin")

admin_site.register(User)
admin_site.register(TOTPDevice)

urlpatterns = [
    path('django_admin/', admin.site.urls),
    path('admin/', admin_site.urls),

    path('', include('home.urls', namespace='home')),
    path('about', views.about, name='about'),
    path('windshild', views.service, name='windshild'),
    path('portfolio', views.portfolio, name='portfolio'),
    path('contact', views.contact, name='contact'),

    path('windshild/<slug:slug>', views.service_detail, name='service_detail'),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots.txt', include('robots.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/models.py
from datetime import datetime
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse


class Service(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=160)
    image_1 = models.ImageField(upload_to='images/')
    alt_1 = models.CharField(max_length=160)
    image_2 = models.ImageField(upload_to='images/')
    alt_2 = models.CharField(max_length=160)
    detail = RichTextUploadingField(blank=True)
    short_detail = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Services'

    def get_absolute_url(self):
        return reverse('service_detail', args=[self.slug])

    def __str__(self):
        return self.title


class About(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=160)
    detail = RichTextUploadingField(blank=True)
    short_detail = models.CharField(max_length=100)
    status = models.CharField(max_length=10, choices=STATUS)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'About'

    def __str__(self):
        return self.title


class Portfolio(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=160)
    status = models.CharField(max_length=10, choices=STATUS)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Portfolio'

    def __str__(self):
        return self.title


class Contact(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    subject = models.CharField(max_length=100)
    message = models.TextField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    contact_date = models.DateTimeField(default=datetime.now, blank=True)
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib import messages
from django.core.mail import send_mail

from .models import About, Contact, Portfolio, Service


def home(request):
    services = Service.objects.all()
    portfolio = Portfolio.objects.order_by('created')[:9]
    about = About.objects.all()
    return render(request, 'index.html', {'services': services, 'portfolio': portfolio, 'about': about})


def about(request):
    about = About.objects.all()
    services = Service.objects.all()
    return render(request, 'about.html', {'about': about, 'services': services})


def service(request):
    services = Service.objects.all()
    about = About.objects.all()
    return render(request, 'service.html', {'services': services, 'about': about})


def service_detail(request, slug):
    service = get_object_or_404(Service, slug=slug)
    about = About.objects.all()
    return render(request, 'service_detail.html', {'service': service, 'about': about})


def portfolio(request):
    portfolio = Portfolio.objects.all()
    services = Service.objects.all()
    about = About.objects.all()
    return render(request, 'portfolio.html', {'portfolio': portfolio, 'services': services, 'about': about})


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        subject = request.POST['subject']
        message = request.POST['message']

        contact = Contact(name=name, email=email, phone=phone,
                          subject=subject, message=message)

        contact.save()

        send_mail(
            subject,  # title
            message,  # message
            'settings.EMAIL_HOST_USER',
            [email],
            fail_silently=False)

        messages.success(
            request, 'Your Message has been received, we will get back soon!')
    services = Service.objects.all
    about = About.objects.all()
    return render(request, 'contact.html', {'services': services, 'about': about})

home/templates/about.html
{% extends 'base.html' %} {% load static %} 

{% block meta %}
		<title>Nairobi&#39;s Number One Windshield Repair Services | Windshild Autoglass Limited</title>
		<link rel="canonical" href="https://www.windshildautoglass.com{{request.path}}">
		<meta property="og:locale" content="en_US" />
		<meta property="og:type" content="website" />
		<meta property="og:title" content="Nairobi&#39;s Number One Windshield Repair Services | Windshild Autoglass Limited" />
		<meta property="og:description" content="Windshild Autoglass Limited, your reliable windscreen repair in Nairobi." />
		<meta property="og:url" content="https://windshildautoglass.com/" />
		<meta property="og:site_name" content="QuickPay Credit Limited" />
		<meta property="article:publisher" content="https://www.facebook.com/windshildautoglass" />
		<meta property="og:image" content="https://windshildautoglass.com/static" />
		<meta property="og:image:width" content="960" />
		<meta property="og:image:height" content="959" />
		<meta property="og:image:type" content="image/jpeg" />
		<meta name="twitter:card" content="summary_large_image" />
		<meta name="twitter:site" content="@windshildautoglass" />
		{% endblock meta %}

{% block content %}

<!--Start breadcrumb area-->
<section class="breadcrumb-area">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumbs text-center">
          <h1>About Windshild Autoglass</h1>
        </div>
      </div>
    </div>
  </div>
</section>
<!--End breadcrumb area-->

<!--Start breadcrumb bottom area-->
<section class="breadcrumb-bottom-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-5 col-sm-5">
        <ul>
          <li><a href="{% url 'home:home' %}">Home</a></li>
          <li><i class="fa fa-angle-right"></i></li>
          <li>About</li>
        </ul>
      </div>
      <div class="col-lg-4 col-md-7 col-sm-7">
        <p>We are here to provide 100% services to our customers</p>
      </div>
    </div>
  </div>
</section>
<!--End breadcrumb bottom area-->

<!--Start customers area-->
<section class="customers-area">
  <div class="container">
    <div class="row">
      {% for rs in about %}
      <div class="col-lg-9 col-md-8">
        <div class="customers-info">
          <div class="sec-title text-left">
            <h1>Know About Us</h1>
            <span class="decor"></span>
          </div>
          <div class="img-holder">
            <img src="{{ rs.image.url }}" alt="{{ rs.alt }}" />
          </div>
          <div class="content">
            <h3>{{ rs.title }}</h3>
            <p>{{ rs.detail | safe }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
      <div class="col-lg-3 col-md-4">
        <div class="customer-support">
          <h4>24/7 Customer Support.</h4>
          <p>
            Windshild Autoglass is your ONE STOP<br />
            solution bringing best car services.
          </p>
          <h3><span class="flaticon-telephone"></span>+254743055367</h3>
          <div class="info-box text-center">
            <p>Mob: +254743055367</p>
            <p>Email: windshildglass@gmail.com</p>
            <div class="social">
              <ul>
                <li>
                  <a href="#"><i class="flaticon-facebook-letter-logo"></i></a>
                </li>
                <li>
                  <a href="#"
                    ><i class="flaticon-twitter-logo-silhouette"></i
                  ></a>
                </li>
                <li>
                  <a href="#"><i class="flaticon-google-plus-logo"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--End customers area-->

<!--Start trusted service area-->
<section class="trusted-service-area">
  <div class="container">
    <div class="row">
      <!--Start single item-->
      <div class="col-md-6 col-sm-12 col-xs-12">
        <div class="single-item">
          <div class="icon-holder">
            <span class="flaticon-social"></span>
          </div>
          <div class="content">
            <h3>Vision</h3>
            <p>
              Our vision is to be the leading global motor vehicle service
              center.
            </p>
          </div>
        </div>
      </div>
      <!--End single item-->
      <!--Start single item-->
      <div class="col-md-6 col-sm-12 col-xs-12">
        <div class="single-item">
          <div class="icon-holder">
            <span class="flaticon-wrench"></span>
          </div>
          <div class="content">
            <h3>Mission</h3>
            <p>
              be market leaders in Windscreen repair and motor vehicle spare
              parts by;
            </p>
            <ul>
              <li>
                Providing best solution to insurance companies; motor vehicle
                owners on windscreen claims management.
              </li>
              <li>Being focused on providing client specific solutions.</li>
              <li>Being efficient and effective in service delivery.</li>
              <li>Maintain world class business performance standard.</li>
            </ul>
          </div>
        </div>
      </div>
      <!--End single item-->
    </div>
  </div>
</section>
<!--End trusted service area-->

<!--Start why choose us area-->
<section class="why-choose-us-area">
  <div class="container">
    <div class="sec-title text-center">
      <h1>Why Choose Us</h1>
      <span class="decor"></span>
    </div>
    <div class="row">
      <!--Start single item-->
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <div class="single-item">
          <div class="icon-holder">
            <span class="flaticon-social"></span>
          </div>
          <div class="content">
            <h3>100% Transparency</h3>
            <p>
              We ensure that you get a well detailed break-up of each minor
              repair work
            </p>
          </div>
        </div>
      </div>
      <!--End single item-->
      <!--Start single item-->
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <div class="single-item">
          <div class="icon-holder">
            <span class="flaticon-wrench"></span>
          </div>
          <div class="content">
            <h3>Genuine Spare Parts</h3>
            <p>
              We useuthorized genuine spare parts &amp; accessories to ensure
              that your
            </p>
          </div>
        </div>
      </div>
      <!--End single item-->
      <!--Start single item-->
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <div class="single-item">
          <div class="icon-holder">
            <span class="flaticon-map"></span>
          </div>
          <div class="content">
            <h3>Trusted &amp; Quality Service</h3>
            <p>
              You can avail our free pickup &amp; drop so that you can just sit
              &amp; relax
            </p>
          </div>
        </div>
      </div>
      <!--End single item-->
      <!--Start single item-->
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <div class="single-item">
          <div class="icon-holder">
            <span class="flaticon-interface-2"></span>
          </div>
          <div class="content">
            <h3>Friendly &#38; Helpfull Team</h3>
            <p>
              We are a friendly &#38; helpful professional group of people in
              autocare.
            </p>
          </div>
        </div>
      </div>
      <!--End single item-->
      <!--Start single item-->
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <div class="single-item">
          <div class="icon-holder">
            <span class="flaticon-transport-2"></span>
          </div>
          <div class="content">
            <h3>free Pickup &#38; Drop</h3>
            <p>
              You can avail our free pickup &#38; drop so that you can just sit
              &#38; relax.
            </p>
          </div>
        </div>
      </div>
      <!--End single item-->
      <!--Start single item-->
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <div class="single-item">
          <div class="icon-holder">
            <span class="flaticon-money"></span>
          </div>
          <div class="content">
            <h3>Zero Upselling</h3>
            <p>
              You can see servicing cost upfront our Service Calculator. Only
              additional.
            </p>
          </div>
        </div>
      </div>
      <!--End single item-->
    </div>
  </div>
</section>
<!--End why choose us area-->

<!--Start Brand area-->
<section class="brand-area about-us-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="brand">
          <!--Start single item-->
          <div class="single-item">
            <a href="#"
              ><img src="img/brand/1.png" alt="Awesome Brand Image"
            /></a>
          </div>
          <!--End single item-->
          <!--Start single item-->
          <div class="single-item">
            <a href="#"
              ><img src="img/brand/2.png" alt="Awesome Brand Image"
            /></a>
          </div>
          <!--End single item-->
          <!--Start single item-->
          <div class="single-item">
            <a href="#"
              ><img src="img/brand/3.png" alt="Awesome Brand Image"
            /></a>
          </div>
          <!--End single item-->
          <!--Start single item-->
          <div class="single-item">
            <a href="#"
              ><img src="img/brand/4.png" alt="Awesome Brand Image"
            /></a>
          </div>
          <!--End single item-->
          <!--Start single item-->
          <div class="single-item">
            <a href="#"
              ><img src="img/brand/5.png" alt="Awesome Brand Image"
            /></a>
          </div>
          <!--End single item-->
          <!--Start single item-->
          <div class="single-item">
            <a href="#"
              ><img src="img/brand/6.png" alt="Awesome Brand Image"
            /></a>
          </div>
          <!--End single item-->
        </div>
      </div>
    </div>
  </div>
</section>
<!--End Brand area-->

{% endblock content %}

home/templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
		<title>Nairobi&#39;s Number One Windshield Repair Services | Windshild Autoglass Limited</title>
		<link rel="canonical" href="https://www.windshildautoglass.com{{request.path}}">
		<meta property="og:locale" content="en_US" />
		<meta property="og:type" content="website" />
		<meta property="og:title" content="Nairobi&#39;s Number One Windshield Repair Services | Windshild Autoglass Limited" />
		<meta property="og:description" content="Windshild Autoglass Limited, your reliable windscreen repair in Nairobi." />
		<meta property="og:url" content="https://windshildautoglass.com/" />
		<meta property="og:site_name" content="QuickPay Credit Limited" />
		<meta property="article:publisher" content="https://www.facebook.com/windshildautoglass" />
		<meta property="og:image" content="https://windshildautoglass.com/static" />
		<meta property="og:image:width" content="960" />
		<meta property="og:image:height" content="959" />
		<meta property="og:image:type" content="image/jpeg" />
		<meta name="twitter:card" content="summary_large_image" />
		<meta name="twitter:site" content="@windshildautoglass" />
		{% endblock meta %}

{% block content %}

<!--Start breadcrumb area-->
<section class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumbs text-center">
                    <h1>Get Touch With Us</h1>
                    <h4>We Are Here For You</h4>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End breadcrumb area-->
    
<!--Start breadcrumb bottom area--> 
<section class="breadcrumb-bottom-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-5 col-sm-5">
                <ul>
                    <li><a href="{% url 'home:home' %}">Home</a></li>
                    <li><i class="fa fa-angle-right"></i></li>
                    <li>Contact</li> 
                </ul>
            </div>
            <div class="col-lg-4 col-md-7 col-sm-7">
                <p>We are here to provide 100% services to our customers</p>
            </div>
        </div>
    </div>
</section>    
<!--End breadcrumb bottom area-->
    
<!--Start contact area-->
<section class="contact-area">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="getin-touch">
                    <div class="sec-title text-left">
                        <h1>Get In Touch</h1>
                        <span class="decor"></span>
                    </div>
                    <h2>We&#39;re Here <br> Let&#39;s Talk</h2>
                    <ul class="contact-info">
                        <li class="address">
                            <div class="icon-holder">
                                <span class="flaticon-map"></span>
                            </div>
                            <div class="content">
                                <h4>Address :</h4>
                                <p>Car Wash, Bunyala Road, Nairobi, Kenya</p>
                            </div>
                        </li>
                        <li class="email">
                            <div class="icon-holder">
                                <span class="flaticon-note"></span>
                            </div>
                            <div class="content">
                                <h4>Ask Anything Here :</h4>
                                <p>windshildglass@gmail.com</p>
                            </div>
                        </li>
                        <li>
                            <div class="icon-holder">
                                <span class="flaticon-telephone"></span>
                            </div>
                            <div class="content">
                                <h4>Call Us:</h4>
                                <p>+254 743 055 367</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-8">
                <div class="contact-form">
                    <div class="sec-title text-left">
                        <h1>Send Message Us</h1>
                        <span class="decor"></span>
                    </div>
                    <form method="POST" action="{% url 'contact' %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <input type="text" name="name" placeholder="Your Name*">
                            </div>
                            <div class="col-md-6">
                                <input type="text" name="email" placeholder="Email Address*">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <input type="text" name="phone" placeholder="Phone">
                            </div>
                            <div class="col-md-6">
                                <input type="text" name="subject" placeholder="Subject*">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <textarea name="message" placeholder="Message*"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <button type="submit">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>    
            </div>
        </div>
    </div>
</section>      
<!--End contact area-->
    
    
{% comment %} <div 
  class="google-map" 
  id="contact-google-map" 
  data-map-lat="-1.2987618784169856" 
  data-map-lng="36.82647328650689" 
  data-icon-path="img/resources/map-marker.png"
  data-map-title="Car Wash, Bunyala Road"
  data-map-zoom="12"
  data-markers='{
            "marker-1": [-1.2987618784169856, 36.82647328650689, "<h4>Windshild Autoglass</h4><p>Bunyala Road, Nairobi, Kenya</p>"],
        }'>

</div> {% endcomment %}

{% endblock content %}

home/templates/footer.html
{% load static %}

<!--Start footer bottom area-->
<footer class="footer-area">
  <div class="footer-middle">
    <div class="container">
      <div class="row">
        <!--Start single footer widget-->
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
          <div class="single-footer-widget">
            <div class="footer-logo">
              <img
                src="{% static 'img/resources/windshild-glass-limited-logo.png' %}"
                height="62px"
                width="256px"
                alt="Wind Shild Glass Logo"
              />
            </div>
            <div class="text">
              <p>
                Windshild Autoglass Limited is an officially registered company
                in Kenya, specifically in Nairobi city's Industrial Area on
                Bunyala Road. Established in July 2018, Windshild Autoglass
                Limited operates as a limited liability company with a primary
                focus on providing specialized services in the replacement of
                motor vehicle windshields, sidefixes, quarter glass, door
                frames, and various spare parts.
              </p>
            </div>
          </div>
        </div>
        <!--End single footer widget-->
        <!--Start single footer widget-->
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
          <div class="single-footer-widget">
            <div class="sec-title text-left">
              <h2>Quick Links</h2>
              <span class="decor"></span>
            </div>
            <ul class="service-list">
              <li>
                <a href="{% url 'home:home' %}"
                  ><i class="fa fa-angle-right" aria-hidden="true"></i>Home</a
                >
              </li>
              <li>
                <a href="{% url 'about' %}"
                  ><i class="fa fa-angle-right" aria-hidden="true"></i>About</a
                >
              </li>
              <li>
                <a href="{% url 'windshild' %}"
                  ><i class="fa fa-angle-right" aria-hidden="true"></i
                  >Windshild</a
                >
              </li>
              <li>
                <a href="{% url 'portfolio' %}"
                  ><i class="fa fa-angle-right" aria-hidden="true"></i
                  >Portfolio</a
                >
              </li>
              <li>
                <a href="{% url 'contact' %}"
                  ><i class="fa fa-angle-right" aria-hidden="true"></i
                  >Contact</a
                >
              </li>
            </ul>
          </div>
        </div>
        <!--End single footer widget-->
        <!--Start single footer widget-->
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
          <div class="single-footer-widget">
            <div class="sec-title text-left">
              <h2>Important Tags</h2>
              <span class="decor"></span>
            </div>
            <ul class="tags-list">
              <li><a href="">Wheel</a></li>
              <li><a href="">Brakes</a></li>
              <li><a href="">Air</a></li>
              <li><a href="">Painting</a></li>
              <li><a href="">Mechanic</a></li>
            </ul>
            <h3>Working Hours:</h3>
            <p class="working-hours-weekdays">
              Weekdays: 09.00am to 6.00pm <br />
              Sunday: Closed
            </p>
          </div>
        </div>
        <!--End single footer widget-->
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-9 col-sm-8 col-xs-12">
          <div class="copy-right">
            <p>
              &copy; {% now "Y" %} Windshild Autoglass Limited. All Rights
              Reserved by
              <a href="https://www.codeworldcreatives.com">Ad-Mastaz</a>
            </p>
          </div>
        </div>
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="footer-social-link">
            <ul>
              <li>
                <a href="#"><i class="flaticon-facebook-letter-logo"></i></a>
              </li>
              <li>
                <a href="#"><i class="flaticon-twitter-logo-silhouette"></i></a>
              </li>
              <li>
                <a href="#"><i class="flaticon-google-plus-logo"></i></a>
              </li>
              <li>
                <a href="#"><i class="flaticon-linkedin-logo"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
<!--End footer bottom area-->